### ISSUE TITLE
yarn failing when no ssh present 

### ISSUE THREAD

**Issue by fhirfly** [LIT-Protocol/CeramicIntegration#8]
In yarn.lock:
```web-streams-polyfill@https://github.com/gwicke/web-streams-polyfill#spec_performance_improvements``` is being fetched with ```git://``` (ssh) instead of ```https://```
```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/gwicke/web-streams-polyfill
Directory: C:\Users\rsasdasd\Projects\CeramicIntegration
Output:
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Unknown error
```
There's much less a guarantee of ssh than https:// suggest you change or state a dependency in the readme of ssh on command line.

**Comment by glitch003** [comment]
Hey, unfortunately, it looks like this is a dependency of https://www.npmjs.com/package/node-web-streams.  I added a note to our Readme that this does need SSH to install.  

Thanks!
